[project]
name = "lesson-02-dependency-upgrade"
version = "0.1.0"
description = "Demo project for updating dependencies with uv"

requires-python = ">=3.8"
dependencies = [
    "scikit-learn==1.2.2",
    "django==4.0.1"
]
